version: '3.8'

services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    ports:
      - "7070:80"  # Mapeia a porta 80 do container para a porta 8080 do host
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
